/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: reizibarrientos (https://sketchfab.com/reizibarrientos)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/7e744a429b9d4041bc43aae7939a4250
title: PurpleHeartAnime
Modifications have been added
*/

export enum PurpleHeartAction {
  Fight = 'solaFighting',
  Kick = 'solakicking',
  HipHop = 'solahiphop',
  BellyDance = 'solaBellyDance',
  SalsaDance = 'solasalsadancing',
  RoboticDance = 'solaRoboticDance',
}
