/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: reizibarrientos (https://sketchfab.com/reizibarrientos)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/7e744a429b9d4041bc43aae7939a4250
title: PurpleHeartAnime
Modifications have been added
*/

import { CharacterStructure } from '../types'

export enum PurpleHeartAction {
  Fight = 'solaFighting',
  Kick = 'solakicking',
  HipHop = 'solahiphop',
  BellyDance = 'solaBellyDance',
  SalsaDance = 'solasalsadancing',
  RoboticDance = 'solaRoboticDance',
}

export const purpleHeartStructure: CharacterStructure<PurpleHeartAction> = {
  path: 'models/purple_heart/scene.gltf',
  groups: [{}, { rotation: [-Math.PI / 2, 0, 0] }, { position: [0, -0.03, 0.04] }],
  actions: {
    [PurpleHeartAction.Fight]: { repeat: false },
    [PurpleHeartAction.Kick]: { repeat: false },
    [PurpleHeartAction.HipHop]: { repeat: true },
    [PurpleHeartAction.BellyDance]: { repeat: true },
    [PurpleHeartAction.SalsaDance]: { repeat: true },
    [PurpleHeartAction.RoboticDance]: { repeat: true },
  },
  bone: 'solana_rootJoint',
  skinnedMeshes: [
    {
      node: 'PurpleHeartV_0',
      material: 'Material__372',
    },
    {
      node: 'PurpleHeartV_1',
      material: 'Material__384',
    },
    {
      node: 'PurpleHeartV_2',
      material: 'Material__396',
    },
  ],
}
